/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ITotal;
import model.Estudante;
import model.Curso;
import javax.swing.*;

/**
 *
 * @author kenandja
 */
public class InscricaoEstudante extends javax.swing.JFrame {
    
    private MainView mainView;
    private ITotal controleController;
    /**
     * Creates new form InscricaoEstudante
     */
    public InscricaoEstudante(MainView mainView, ITotal controleController) {
        initComponents();
        this.mainView = mainView;
        this.controleController = controleController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInscricaoEstudante = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonListarEstudantes = new javax.swing.JButton();
        jButtonListarCursos = new javax.swing.JButton();
        jButtonMatriculaEstudante = new javax.swing.JButton();
        jButtonDesmatriculaEstudante = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEmailEstudante = new javax.swing.JTextField();
        jTextFieldIdCurso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMostrarListas = new javax.swing.JTextArea();
        jButtonListarCursosEstudante = new javax.swing.JButton();
        jButtonListarEstudantesCurso = new javax.swing.JButton();
        jLabelInscricaoEstudante = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cursos Online");
        setResizable(false);

        jPanelInscricaoEstudante.setBackground(new java.awt.Color(153, 102, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jButtonListarEstudantes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonListarEstudantes.setForeground(new java.awt.Color(0, 0, 0));
        jButtonListarEstudantes.setText("Listar Estudantes");
        jButtonListarEstudantes.setToolTipText("");
        jButtonListarEstudantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarEstudantesActionPerformed(evt);
            }
        });

        jButtonListarCursos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonListarCursos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonListarCursos.setText("Listar Cursos");
        jButtonListarCursos.setToolTipText("");
        jButtonListarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarCursosActionPerformed(evt);
            }
        });

        jButtonMatriculaEstudante.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonMatriculaEstudante.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMatriculaEstudante.setText("Matricular");
        jButtonMatriculaEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatriculaEstudanteActionPerformed(evt);
            }
        });

        jButtonDesmatriculaEstudante.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonDesmatriculaEstudante.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDesmatriculaEstudante.setText("Desmatricular");
        jButtonDesmatriculaEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesmatriculaEstudanteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Email do Aluno:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Id do Curso:");

        jTextFieldEmailEstudante.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmailEstudante.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldEmailEstudante.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldEmailEstudante.setToolTipText("Digite o e-mail");
        jTextFieldEmailEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailEstudanteActionPerformed(evt);
            }
        });

        jTextFieldIdCurso.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIdCurso.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldIdCurso.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldIdCurso.setToolTipText("Digite o ID do curso");

        jTextAreaMostrarListas.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaMostrarListas.setColumns(20);
        jTextAreaMostrarListas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextAreaMostrarListas.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaMostrarListas.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMostrarListas);

        jButtonListarCursosEstudante.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonListarCursosEstudante.setForeground(new java.awt.Color(0, 0, 0));
        jButtonListarCursosEstudante.setText("Listar Cursos do Estudante");
        jButtonListarCursosEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarCursosEstudanteActionPerformed(evt);
            }
        });

        jButtonListarEstudantesCurso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonListarEstudantesCurso.setForeground(new java.awt.Color(0, 0, 0));
        jButtonListarEstudantesCurso.setText("Listar Estudantes do Curso");
        jButtonListarEstudantesCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarEstudantesCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEmailEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonDesmatriculaEstudante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(jButtonListarEstudantesCurso))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonMatriculaEstudante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonListarCursosEstudante))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButtonListarCursos)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonListarEstudantes)))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMatriculaEstudante)
                            .addComponent(jButtonListarCursosEstudante)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldEmailEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDesmatriculaEstudante)
                    .addComponent(jButtonListarEstudantesCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarCursos)
                    .addComponent(jButtonListarEstudantes))
                .addGap(29, 29, 29))
        );

        jLabelInscricaoEstudante.setFont(new java.awt.Font("Nimbus Roman", 1, 42)); // NOI18N
        jLabelInscricaoEstudante.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInscricaoEstudante.setText("Inscrição");
        jLabelInscricaoEstudante.setToolTipText("");

        javax.swing.GroupLayout jPanelInscricaoEstudanteLayout = new javax.swing.GroupLayout(jPanelInscricaoEstudante);
        jPanelInscricaoEstudante.setLayout(jPanelInscricaoEstudanteLayout);
        jPanelInscricaoEstudanteLayout.setHorizontalGroup(
            jPanelInscricaoEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInscricaoEstudanteLayout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabelInscricaoEstudante)
                .addContainerGap(326, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInscricaoEstudanteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanelInscricaoEstudanteLayout.setVerticalGroup(
            jPanelInscricaoEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInscricaoEstudanteLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabelInscricaoEstudante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInscricaoEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInscricaoEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private /*List <Estudante>*/ void listarEstudantes () {
        jTextAreaMostrarListas.setText("");
        for(Estudante estudante : controleController.listarEstudantes()) {
            jTextAreaMostrarListas.append(estudante.getNome() + " || " + estudante.getEmail() + "\n");
        }
    }
    
    private void jButtonListarEstudantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarEstudantesActionPerformed
        // TODO add your handling code here:
        listarEstudantes();
    }//GEN-LAST:event_jButtonListarEstudantesActionPerformed

    private /*List <Curso>*/ void listarCursos () {
        jTextAreaMostrarListas.setText("");
        for(Curso curso: controleController.listarCursos()) {
            jTextAreaMostrarListas.append(curso.getNome() + " || ID: " + curso.getId() + "\n" 
            + curso.getDescricao() + "\n" + "Valor: " + curso.getPreco() + "\n\n");
        }
    }
    
    private void jButtonListarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarCursosActionPerformed
        // TODO add your handling code here:
        listarCursos();
    }//GEN-LAST:event_jButtonListarCursosActionPerformed

    private void matricularEstudanteNoCurso() {
        jTextAreaMostrarListas.setText("");
            try {
                Estudante estudante = controleController.obterEstudante(jTextFieldEmailEstudante.getText());
                Curso curso = controleController.obterCurso(jTextFieldIdCurso.getText());
                controleController.matricularEstudanteCurso(estudante, curso);
                JOptionPane.showMessageDialog(null, "Matrícula efetuada! Aproveite!");
            } catch(Exception ex) {
                  JOptionPane.showMessageDialog(null, "Dados inválidos. Por favor, verifique.");
                  //JOptionPane.showMessageDialog(null, "Erro: " + ex);
            }
    }
    
    private void jButtonMatriculaEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatriculaEstudanteActionPerformed
        // TODO add your handling code here:
        matricularEstudanteNoCurso();
    }//GEN-LAST:event_jButtonMatriculaEstudanteActionPerformed

    private void desmatricularEstudanteDoCurso() {
        jTextAreaMostrarListas.setText("");
        try {
            Estudante estudante = controleController.obterEstudante(jTextFieldEmailEstudante.getText());
            Curso curso = controleController.obterCurso(jTextFieldIdCurso.getText());
            controleController.desmatricularEstudanteCurso(estudante, curso);
            JOptionPane.showMessageDialog(null, "Desmatrícula feita. Volte sempre!");
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Dados inválidos. Por favor, verifique.");
            //JOptionPane.showMessageDialog(null, "Erro: " + ex);
        }
        
    }
    
    private void jButtonDesmatriculaEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesmatriculaEstudanteActionPerformed
        // TODO add your handling code here:
        desmatricularEstudanteDoCurso();
    }//GEN-LAST:event_jButtonDesmatriculaEstudanteActionPerformed

    private void jTextFieldEmailEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailEstudanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailEstudanteActionPerformed

    private void listarCursosDoEstudante() {
        jTextAreaMostrarListas.setText("");
        try {
            String email = jTextFieldEmailEstudante.getText();
            Estudante estudante = controleController.obterEstudante(email);
            for(Curso curso : estudante.getCursosEstudante()) {
                jTextAreaMostrarListas.append(curso.getNome() + "\n");
            } 
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Dados inválidos. Por favor, verifique.");
        }
    }
    
    private void jButtonListarCursosEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarCursosEstudanteActionPerformed
        // TODO add your handling code here:
        listarCursosDoEstudante();
    }//GEN-LAST:event_jButtonListarCursosEstudanteActionPerformed

    private void listarEstudantesDoCurso() {
        jTextAreaMostrarListas.setText("");
        try {
            String id = jTextFieldIdCurso.getText();
            Curso curso = controleController.obterCurso(id);
            for(Estudante estudante : curso.getEstudantesCurso()) {
                jTextAreaMostrarListas.append(estudante.getNome() + "\n");
            } 
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Dados inválidos. Por favor, verifique.");
        }
        
    }
    
    private void jButtonListarEstudantesCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarEstudantesCursoActionPerformed
        // TODO add your handling code here:
        listarEstudantesDoCurso();
    }//GEN-LAST:event_jButtonListarEstudantesCursoActionPerformed

    
    /*private void display() {
        JScrollPane scrollpane = new JScrollPane(jTextAreaMostrarListas);
        //jTextAreaMostrarListas = listarCursos();
    }*/
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InscricaoEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InscricaoEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InscricaoEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InscricaoEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InscricaoEstudante().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDesmatriculaEstudante;
    private javax.swing.JButton jButtonListarCursos;
    private javax.swing.JButton jButtonListarCursosEstudante;
    private javax.swing.JButton jButtonListarEstudantes;
    private javax.swing.JButton jButtonListarEstudantesCurso;
    private javax.swing.JButton jButtonMatriculaEstudante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelInscricaoEstudante;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelInscricaoEstudante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMostrarListas;
    private javax.swing.JTextField jTextFieldEmailEstudante;
    private javax.swing.JTextField jTextFieldIdCurso;
    // End of variables declaration//GEN-END:variables
}
