/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author kenandja
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuCursos = new javax.swing.JMenu();
        jMenuInscricao = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCurso = new javax.swing.JMenuItem();
        jMenuItemEstudante = new javax.swing.JMenuItem();
        jMenuItemInstrutor = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plataforma Codar com Tema Escuro");
        setResizable(false);

        jMenuCursos.setText("Cursos");
        jMenuCursos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jMenuInscricao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuInscricao.setForeground(new java.awt.Color(0, 0, 0));
        jMenuInscricao.setIcon(new javax.swing.ImageIcon("/home/kenandja/NetBeansProjects/seta.png")); // NOI18N
        jMenuInscricao.setText("Inscrição");
        jMenuCursos.add(jMenuInscricao);

        jMenuBarMain.add(jMenuCursos);

        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jMenuItemCurso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItemCurso.setIcon(new javax.swing.ImageIcon("/home/kenandja/NetBeansProjects/seta.png")); // NOI18N
        jMenuItemCurso.setText("Curso");
        jMenuCadastro.add(jMenuItemCurso);

        jMenuItemEstudante.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItemEstudante.setIcon(new javax.swing.ImageIcon("/home/kenandja/NetBeansProjects/seta.png")); // NOI18N
        jMenuItemEstudante.setText("Estudante");
        jMenuCadastro.add(jMenuItemEstudante);

        jMenuItemInstrutor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItemInstrutor.setIcon(new javax.swing.ImageIcon("/home/kenandja/NetBeansProjects/seta.png")); // NOI18N
        jMenuItemInstrutor.setText("Instrutor");
        jMenuCadastro.add(jMenuItemInstrutor);

        jMenuBarMain.add(jMenuCadastro);

        jMenuSair.setText("Sair");
        jMenuSair.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jMenuBarMain.add(jMenuSair);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuCursos;
    private javax.swing.JMenuItem jMenuInscricao;
    private javax.swing.JMenuItem jMenuItemCurso;
    private javax.swing.JMenuItem jMenuItemEstudante;
    private javax.swing.JMenuItem jMenuItemInstrutor;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables
}
